package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// pkgverify_test.go pins the package-integrity contract added for the
// pre-release security audit finding C2-I-03 ("no checksum or signature
// verification in the entire install path").
//
// The behaviour under test, in the words of the finding: the installer used to
// accept arbitrary bytes and install them as root (`opkg --force-downgrade …`,
// `apk add --allow-untrusted …`), so a corrupted, truncated or substituted
// package produced a GREEN "done" step. These tests drive the real verifier and
// assert that (a) bytes matching the published digest pass, (b) bytes that do
// not match FAIL, naming the asset and both digests, (c) a package that cannot
// be the expected format FAILS, and (d) a release that publishes no digest is
// reported as UNVERIFIED — never as a pass.

// fakeIPK / fakeAPK are structurally plausible package blobs (correct magic,
// above the size floor) used as stand-ins for the ~8 MB release assets.
func fakeIPK(n int) []byte {
	b := make([]byte, n)
	copy(b, []byte{0x1f, 0x8b, 0x08, 0x00})
	for i := 4; i < n; i++ {
		b[i] = byte(i * 7)
	}
	return b
}

func fakeAPK(n int) []byte {
	b := make([]byte, n)
	copy(b, []byte(apkMagic))
	for i := 4; i < n; i++ {
		b[i] = byte(i*13 + 5)
	}
	return b
}

func digestOf(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

func TestAssetNameFromURL(t *testing.T) {
	cases := []struct{ in, want string }{
		{"https://github.com/FreedomTechFeed/packages/releases/download/v0.6.0-alpha2-pre9/tollgate-wrt_0.6.0_alpha2_pre9_aarch64_cortex-a53.ipk",
			"tollgate-wrt_0.6.0_alpha2_pre9_aarch64_cortex-a53.ipk"},
		{"https://github.com/o/r/releases/download/v1/name.apk?x=1", "name.apk"},
		{"", ""},
	}
	for _, tc := range cases {
		if got := assetNameFromURL(tc.in); got != tc.want {
			t.Errorf("assetNameFromURL(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestReleaseAssetRefAndDir(t *testing.T) {
	url := "https://github.com/FreedomTechFeed/packages/releases/download/v0.6.0-alpha2-pre9/tollgate-wrt_0.6.0_alpha2_pre9_aarch64_cortex-a53.ipk"
	owner, repo, tag, name, ok := releaseAssetRef(url)
	if !ok {
		t.Fatalf("releaseAssetRef(%q) not recognised", url)
	}
	if owner != "FreedomTechFeed" || repo != "packages" || tag != "v0.6.0-alpha2-pre9" {
		t.Errorf("releaseAssetRef = (%q, %q, %q), want (FreedomTechFeed, packages, v0.6.0-alpha2-pre9)", owner, repo, tag)
	}
	if want := "tollgate-wrt_0.6.0_alpha2_pre9_aarch64_cortex-a53.ipk"; name != want {
		t.Errorf("asset name = %q, want %q", name, want)
	}
	if got, want := releaseAssetDir(url), "https://github.com/FreedomTechFeed/packages/releases/download/v0.6.0-alpha2-pre9/"; got != want {
		t.Errorf("releaseAssetDir = %q, want %q", got, want)
	}
	// A non-release URL has no API ref and no manifest directory — the verifier
	// must not invent one.
	if _, _, _, _, ok := releaseAssetRef("https://example.com/tollgate-wrt.ipk"); ok {
		t.Errorf("releaseAssetRef accepted a non-GitHub-release URL")
	}
	if got := releaseAssetDir("https://example.com/tollgate-wrt.ipk"); got != "" {
		t.Errorf("releaseAssetDir(non-release URL) = %q, want \"\"", got)
	}
}

func TestNormalizeDigest(t *testing.T) {
	good := strings.Repeat("ab", 32)
	cases := []struct{ in, want string }{
		{good, good},
		{"sha256:" + good, good},
		{"SHA256:" + strings.ToUpper(good), good},
		{"  " + good + "\n", good},
		{strings.Repeat("ab", 31), ""}, // too short
		{strings.Repeat("zz", 32), ""}, // not hex
		{"sha512:" + good, ""},         // wrong algorithm prefix
		{"", ""},                       //
		{"MD5:notahash", ""},           //
	}
	for _, tc := range cases {
		if got := normalizeDigest(tc.in); got != tc.want {
			t.Errorf("normalizeDigest(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestParseChecksumManifestFor(t *testing.T) {
	want := digestOf([]byte("payload"))
	other := digestOf([]byte("other"))
	name := "tollgate-wrt_0.6.0_alpha2_pre9_aarch64_cortex-a53.ipk"

	manifest := strings.Join([]string{
		"# generated by the feed",
		"",
		other + "  tollgate-wrt_0.6.0_alpha2_pre9_x86_64.ipk",
		want + "  " + name,
		"garbage line",
		"zzzz  " + name,
	}, "\n") + "\r\n"

	if got := parseChecksumManifestFor([]byte(manifest), name); got != want {
		t.Errorf("parseChecksumManifestFor = %q, want %q (the entry for our asset)", got, want)
	}
	// Binary-mode markers, "./" prefixes and CRLF are all accepted.
	for _, variant := range []string{
		want + " *" + name,
		want + "  ./" + name,
		want + "\t" + name + "\r\n",
	} {
		if got := parseChecksumManifestFor([]byte(variant), name); got != want {
			t.Errorf("parseChecksumManifestFor(%q) = %q, want %q", variant, got, want)
		}
	}
	// An entry for a DIFFERENT asset must never satisfy the lookup — that is
	// the whole point of matching on the name and not just "some digest".
	if got := parseChecksumManifestFor([]byte(other+"  tollgate-wrt_0.6.0_alpha2_pre9_x86_64.ipk"), name); got != "" {
		t.Errorf("parseChecksumManifestFor matched another asset's entry: %q", got)
	}
	if got := parseChecksumManifestFor([]byte("no digests here"), name); got != "" {
		t.Errorf("parseChecksumManifestFor(no entries) = %q, want \"\"", got)
	}
}

func TestPackageLooksStructural(t *testing.T) {
	if err := packageLooksStructural(".ipk", fakeIPK(minPackageBytes+1)); err != nil {
		t.Errorf("a gzip .ipk above the size floor must pass the structural check: %v", err)
	}
	if err := packageLooksStructural(".apk", fakeAPK(minPackageBytes+1)); err != nil {
		t.Errorf("an ADB .apk above the size floor must pass the structural check: %v", err)
	}
	if err := packageLooksStructural(".ipk", make([]byte, minPackageBytes-1)); err == nil {
		t.Errorf("a package below the size floor must be rejected")
	}
	// The classic failure this catches: an HTML or JSON error page saved as the
	// package by a redirect or a captive portal.
	if err := packageLooksStructural(".ipk", []byte("<!DOCTYPE html><html>404 Not Found"+strings.Repeat(" ", minPackageBytes))); err == nil {
		t.Errorf("an HTML error page must not pass as a .ipk")
	}
	if err := packageLooksStructural(".apk", fakeIPK(minPackageBytes+1)); err == nil {
		t.Errorf("a gzip blob must not pass as an ADB .apk")
	}
	// Only .ipk/.apk have magic to check; other extensions must not be refused
	// on magic grounds (the dev/provenance paths use this helper too).
	if err := packageLooksStructural(".bin", fakeIPK(minPackageBytes+1)); err != nil {
		t.Errorf("unknown extension should not fail the magic check: %v", err)
	}
}

// fakeReleaseServer serves a release layout: optionally a SHA256SUMS manifest,
// optionally a per-asset .sha256 sidecar, and optionally the GitHub API.
func fakeReleaseServer(t *testing.T, assetName string, digest string, withManifest, withSidecar, withAPI bool) (*httptest.Server, string, string) {
	t.Helper()
	mux := http.NewServeMux()
	assetPath := "/FreedomTechFeed/packages/releases/download/v0.6.0-alpha2-pre9/" + assetName
	mux.HandleFunc(assetPath, func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, "asset bytes")
	})
	if withManifest {
		mux.HandleFunc("/FreedomTechFeed/packages/releases/download/v0.6.0-alpha2-pre9/"+sha256SumsAssetName, func(w http.ResponseWriter, r *http.Request) {
			fmt.Fprintf(w, "%s  %s\n", digest, assetName)
		})
	}
	if withSidecar {
		mux.HandleFunc(assetPath+sha256SidecarSuffix, func(w http.ResponseWriter, r *http.Request) {
			fmt.Fprintf(w, "%s  %s\n", digest, assetName)
		})
	}
	if withAPI {
		mux.HandleFunc("/repos/FreedomTechFeed/packages/releases/tags/v0.6.0-alpha2-pre9", func(w http.ResponseWriter, r *http.Request) {
			fmt.Fprintf(w, `{"tag_name":"v0.6.0-alpha2-pre9","assets":[{"name":%q,"digest":"sha256:%s"}]}`, assetName, digest)
		})
	}
	srv := httptest.NewServer(mux)
	t.Cleanup(srv.Close)
	// The fixture serves a release layout over loopback, so the release-asset
	// URL shape must be recognised for the host the fixture actually uses.
	prevHosts := githubReleaseHosts
	githubReleaseHosts = append(append([]string{}, prevHosts...), "127.0.0.1")
	t.Cleanup(func() { githubReleaseHosts = prevHosts })
	return srv, srv.URL + assetPath, srv.URL
}

func TestPublishedDigestSourcePrecedence(t *testing.T) {
	const assetName = "tollgate-wrt_0.6.0_alpha2_pre9_aarch64_cortex-a53.ipk"
	want := digestOf([]byte("package"))

	t.Run("SHA256SUMS manifest wins, but is same-origin so NOT independent", func(t *testing.T) {
		srv, assetURL, apiBase := fakeReleaseServer(t, assetName, want, true, true, true)
		_ = srv
		old := githubAPIBase
		githubAPIBase = apiBase
		t.Cleanup(func() { githubAPIBase = old })

		got, source, independent := publishedDigestForAsset(assetURL)
		if got != want {
			t.Fatalf("digest = %q, want %q", got, want)
		}
		if !strings.Contains(source, sha256SumsAssetName) {
			t.Errorf("source = %q, want it to name the %s manifest (the preferred, signable source)", source, sha256SumsAssetName)
		}
		if independent {
			t.Errorf("the %s manifest was reported as an INDEPENDENT anchor; it is fetched from the asset's own host, so a host serving altered bytes also serves the digest (cold review finding 2)", sha256SumsAssetName)
		}
	})

	t.Run("sidecar used when no manifest is published, and is same-origin too", func(t *testing.T) {
		_, assetURL, apiBase := fakeReleaseServer(t, assetName, want, false, true, true)
		old := githubAPIBase
		githubAPIBase = apiBase
		t.Cleanup(func() { githubAPIBase = old })

		got, source, independent := publishedDigestForAsset(assetURL)
		if got != want {
			t.Fatalf("digest = %q, want %q", got, want)
		}
		if !strings.Contains(source, sha256SidecarSuffix) {
			t.Errorf("source = %q, want the per-asset sidecar", source)
		}
		if independent {
			t.Errorf("the per-asset sidecar was reported as an INDEPENDENT anchor; it is same-origin (cold review finding 2)")
		}
	})

	t.Run("GitHub API digest used when the release publishes no manifest, and IS independent", func(t *testing.T) {
		// This is the state of every feed release today (verified 2026-09-23:
		// v0.6.0-alpha2-pre9 carries 14 assets, no SHA256SUMS).
		_, assetURL, apiBase := fakeReleaseServer(t, assetName, want, false, false, true)
		old := githubAPIBase
		githubAPIBase = apiBase
		t.Cleanup(func() { githubAPIBase = old })

		got, source, independent := publishedDigestForAsset(assetURL)
		if got != want {
			t.Fatalf("digest = %q, want %q", got, want)
		}
		if !strings.Contains(source, "GitHub release API") {
			t.Errorf("source = %q, want the GitHub release API", source)
		}
		if !independent {
			t.Errorf("the GitHub release API digest must be reported as an independent anchor (different origin from the package bytes)")
		}
	})

	t.Run("nothing published yields no digest", func(t *testing.T) {
		_, assetURL, apiBase := fakeReleaseServer(t, assetName, want, false, false, true)
		old := githubAPIBase
		// Point the API elsewhere so the release lookup 404s: no manifest, no
		// sidecar, no API server -> the release publishes nothing we can use.
		githubAPIBase = apiBase + "/nonexistent"
		t.Cleanup(func() { githubAPIBase = old })

		got, source, independent := publishedDigestForAsset(assetURL)
		if got != "" || source != "" || independent {
			t.Errorf("publishedDigestForAsset = (%q, %q, %v), want (\"\", \"\", false) so the caller reports UNVERIFIED", got, source, independent)
		}
	})

	t.Run("API asset with an empty digest field yields nothing", func(t *testing.T) {
		mux := http.NewServeMux()
		mux.HandleFunc("/repos/o/r/releases/tags/v1", func(w http.ResponseWriter, r *http.Request) {
			fmt.Fprint(w, `{"assets":[{"name":"`+assetName+`","digest":""}]}`)
		})
		srv := httptest.NewServer(mux)
		t.Cleanup(srv.Close)
		old := githubAPIBase
		githubAPIBase = srv.URL
		t.Cleanup(func() { githubAPIBase = old })

		got, source, independent := publishedDigestForAsset("https://github.com/o/r/releases/download/v1/" + assetName)
		if got != "" || source != "" || independent {
			t.Errorf("publishedDigestForAsset = (%q, %q, %v), want (\"\", \"\", false) — an empty digest is not a pass", got, source, independent)
		}
	})
}

func TestVerifyPackageBytesVerdicts(t *testing.T) {
	const assetName = "tollgate-wrt_0.6.0_alpha2_pre9_aarch64_cortex-a53.ipk"
	good := fakeIPK(minPackageBytes + 512)
	goodDigest := digestOf(good)

	t.Run("matching digest from the independent API anchor is verified", func(t *testing.T) {
		// The API digest is the ONLY independent source today (different origin
		// from the package bytes), so it is what a green verdict must rest on.
		_, assetURL, apiBase := fakeReleaseServer(t, assetName, goodDigest, false, false, true)
		old := githubAPIBase
		githubAPIBase = apiBase
		t.Cleanup(func() { githubAPIBase = old })

		v := verifyPackageBytes(assetURL, ".ipk", good)
		if !v.verified() || v.fatal() {
			t.Fatalf("verdict = %+v, want verified and non-fatal", v)
		}
		if v.Want != goodDigest || v.Got != goodDigest {
			t.Errorf("verdict digests = (%q, %q), want both %q", v.Want, v.Got, goodDigest)
		}
		if !strings.Contains(v.suffix(), "verified") {
			t.Errorf("suffix = %q, want a verified marker for the install step detail", v.suffix())
		}
	})

	t.Run("same-origin manifest digest is UNVERIFIED, never a pass", func(t *testing.T) {
		// Cold cross-family review 2026-09-23, finding 2: the manifest/sidecar
		// are fetched from the same host that served the package, so a host
		// serving altered bytes would serve a matching digest too. A match
		// there must not be reported as verification.
		_, assetURL, apiBase := fakeReleaseServer(t, assetName, goodDigest, true, true, false)
		old := githubAPIBase
		githubAPIBase = apiBase + "/nonexistent" // no API answer: manifest/sidecar only
		t.Cleanup(func() { githubAPIBase = old })

		v := verifyPackageBytes(assetURL, ".ipk", good)
		if v.verified() {
			t.Fatalf("a same-origin digest match was reported as VERIFIED: %+v", v)
		}
		if v.Status != "unverified" || v.fatal() {
			t.Fatalf("verdict = %+v, want unverified and non-fatal", v)
		}
		if !strings.Contains(v.Detail, "SAME HOST") {
			t.Errorf("detail = %q, want it to explain the same-origin limitation", v.Detail)
		}
		if !strings.Contains(v.suffix(), "NOT VERIFIED") {
			t.Errorf("suffix = %q, want the install step to mark this as not verified", v.suffix())
		}
	})

	t.Run("single flipped byte is fatal and names both digests", func(t *testing.T) {
		// The attack/accident this exists for: one bit of the package differs
		// from what the release published. Before this change the bytes were
		// installed as root and the step rendered green.
		corrupted := append([]byte(nil), good...)
		corrupted[len(corrupted)/2] ^= 0x01
		if digestOf(corrupted) == goodDigest {
			t.Fatal("fixture broken: the corrupted copy has the published digest")
		}
		_, assetURL, apiBase := fakeReleaseServer(t, assetName, goodDigest, false, false, true)
		old := githubAPIBase
		githubAPIBase = apiBase
		t.Cleanup(func() { githubAPIBase = old })

		v := verifyPackageBytes(assetURL, ".ipk", corrupted)
		if v.Status != "mismatch" || !v.fatal() {
			t.Fatalf("verdict = %+v, want a fatal mismatch", v)
		}
		for _, want := range []string{assetName, goodDigest, digestOf(corrupted)} {
			if !strings.Contains(v.Detail, want) {
				t.Errorf("failure text does not name %q:\n%s", want, v.Detail)
			}
		}
		if v.Want != goodDigest || v.Got != digestOf(corrupted) {
			t.Errorf("verdict digests = (%q, %q), want (%q, %q)", v.Want, v.Got, goodDigest, digestOf(corrupted))
		}
	})

	t.Run("no published digest is unverified, never a pass", func(t *testing.T) {
		_, assetURL, apiBase := fakeReleaseServer(t, assetName, goodDigest, false, false, true)
		old := githubAPIBase
		githubAPIBase = apiBase + "/nonexistent"
		t.Cleanup(func() { githubAPIBase = old })

		v := verifyPackageBytes(assetURL, ".ipk", good)
		if v.Status != "unverified" {
			t.Fatalf("verdict = %+v, want unverified", v)
		}
		if v.verified() || v.fatal() {
			t.Errorf("unverified must be neither a pass nor fatal by itself: %+v", v)
		}
		if !strings.Contains(v.Detail, "UNVERIFIED") {
			t.Errorf("detail = %q, want it to say the bytes are UNVERIFIED", v.Detail)
		}
		if !strings.Contains(v.suffix(), "NOT VERIFIED") {
			t.Errorf("suffix = %q, want the step detail to mark the install as not verified", v.suffix())
		}
	})

	t.Run("wrong format is fatal before any lookup", func(t *testing.T) {
		v := verifyPackageBytes("https://example.com/tollgate-wrt.ipk", ".ipk", []byte("<!DOCTYPE html>"+strings.Repeat(" ", minPackageBytes)))
		if v.Status != "malformed" || !v.fatal() {
			t.Fatalf("verdict = %+v, want a fatal malformed verdict", v)
		}
		if !strings.Contains(v.Detail, "REFUSING") {
			t.Errorf("detail = %q, want it to refuse explicitly", v.Detail)
		}
	})
}

func TestCheckPackageBytesPolicy(t *testing.T) {
	const assetName = "tollgate-wrt_0.6.0_alpha2_pre9_aarch64_cortex-a53.ipk"
	good := fakeIPK(minPackageBytes + 512)
	goodDigest := digestOf(good)

	newJob := func() *Job {
		j := newJob("192.0.2.1")
		j.Steps = []Step{{Status: "pending"}, {Status: "pending"}, {Status: "pending"}, {Status: "pending"}, {Status: "pending"}, {Status: "pending"}, {Status: "pending"}}
		return j
	}

	t.Run("mismatch is fatal and logged as an ERROR", func(t *testing.T) {
		_, assetURL, apiBase := fakeReleaseServer(t, assetName, goodDigest, true, false, true)
		old := githubAPIBase
		githubAPIBase = apiBase
		t.Cleanup(func() { githubAPIBase = old })

		job := newJob()
		bad := append([]byte(nil), good...)
		bad[10] ^= 0xff
		v, err := checkPackageBytes(job, assetURL, ".ipk", bad)
		if err == nil {
			t.Fatalf("checkPackageBytes returned nil error for tampered bytes (verdict %+v)", v)
		}
		if !v.fatal() {
			t.Errorf("verdict = %+v, want fatal", v)
		}
		if !logContains(job, "ERROR") || !logContains(job, "MISMATCH") {
			t.Errorf("job log does not record the tamper:\n%s", jobLog(job))
		}
	})

	t.Run("unverified is a WARNING by default and FATAL when required", func(t *testing.T) {
		_, assetURL, apiBase := fakeReleaseServer(t, assetName, goodDigest, false, false, true)
		oldAPI := githubAPIBase
		githubAPIBase = apiBase + "/nonexistent"
		t.Cleanup(func() { githubAPIBase = oldAPI })

		job := newJob()
		_, err := checkPackageBytes(job, assetURL, ".ipk", good)
		if err != nil {
			t.Fatalf("unverified bytes must not fail the deploy by default: %v", err)
		}
		if !logContains(job, "WARNING") {
			t.Errorf("job log does not warn about unverified bytes:\n%s", jobLog(job))
		}

		t.Setenv(requirePkgDigestEnv, "1")
		job2 := newJob()
		v, err := checkPackageBytes(job2, assetURL, ".ipk", good)
		if err == nil {
			t.Fatalf("with %s=1 an unverified package must be fatal (verdict %+v)", requirePkgDigestEnv, v)
		}
		if !strings.Contains(err.Error(), requirePkgDigestEnv) {
			t.Errorf("error %q should name the opt-in that made it fatal", err)
		}
	})
}

func TestRequirePackageDigestEnvParsing(t *testing.T) {
	for _, on := range []string{"1", "true", "TRUE", "yes", "on", " on "} {
		if !requirePackageDigest(func(string) string { return on }) {
			t.Errorf("requirePackageDigest(%q) = false, want true", on)
		}
	}
	for _, off := range []string{"", "0", "false", "no", "off", "banana"} {
		if requirePackageDigest(func(string) string { return off }) {
			t.Errorf("requirePackageDigest(%q) = true, want false", off)
		}
	}
}

func TestRouterFileSHA256WithoutClient(t *testing.T) {
	// No SSH client (the deploy failed earlier) must yield "unverifiable", not
	// an empty string that a caller could mistake for a match.
	if got := routerFileSHA256(nil, "/tmp/tollgate-wrt.ipk"); got != "" {
		t.Errorf("routerFileSHA256(nil, …) = %q, want \"\"", got)
	}
}

// ---- job-log helpers (kept local to this file to avoid touching other tests)

func logContains(job *Job, substr string) bool {
	job.mu.Lock()
	defer job.mu.Unlock()
	for _, l := range job.Log {
		if strings.Contains(l.Msg, substr) {
			return true
		}
	}
	return false
}

func jobLog(job *Job) string {
	job.mu.Lock()
	defer job.mu.Unlock()
	var b strings.Builder
	for _, l := range job.Log {
		b.WriteString(l.Msg)
		b.WriteString("\n")
	}
	return b.String()
}

// TestLivePackageDigestRejectsCorruptedBytes is the end-to-end proof for
// C2-I-03, run against the real pinned feed release (like the repo's other
// live tests it is skipped under -short).
//
// It asserts three things, in order:
//
//  1. the pinned release PUBLISHES a sha256 for the pinned asset — if that
//     stops being true the verifier has gone blind, which must be a loud test
//     failure rather than a silent "unverified" at deploy time;
//  2. the real downloaded bytes match it (so the verifier is not merely
//     self-consistent — it agrees with the artifact customers install);
//  3. a single flipped byte is a FATAL mismatch, i.e. tampering with the
//     package as it travels or at rest in the staging cache cannot be
//     installed as root.
func TestLivePackageDigestRejectsCorruptedBytes(t *testing.T) {
	if testing.Short() {
		t.Skip("live package-digest check skipped: -short mode (CI-parity runs without -short)")
	}
	assetURL := feedAssetURL("aarch64_cortex-a53", ".ipk")

	published, source, independent := publishedDigestForAsset(assetURL)
	if published == "" {
		t.Fatalf("the pinned feed release %s publishes no sha256 for %s (checked %s, the per-asset .sha256 sidecar, and the GitHub release API) — package integrity cannot be verified at deploy time",
			feedReleaseTag, assetNameFromURL(assetURL), sha256SumsAssetName)
	}
	if !independent {
		t.Fatalf("the digest for the pinned feed release came from %q and is NOT an independent anchor — a green verdict must not rest on same-origin data (cold review finding 2)", source)
	}

	data, err := httpGetFile(assetURL)
	if err != nil {
		t.Fatalf("downloading %s: %v", assetURL, err)
	}
	if err := packageLooksStructural(".ipk", data); err != nil {
		t.Fatalf("the real release asset failed the structural check: %v", err)
	}
	v := verifyPackageBytes(assetURL, ".ipk", data)
	if !v.verified() {
		t.Fatalf("real release bytes (%d bytes) did not verify against the digest published by the %s: %+v", len(data), source, v)
	}
	t.Logf("verified %s (%d bytes) against %s: sha256 %s", assetNameFromURL(assetURL), len(data), source, v.Want)

	corrupted := append([]byte(nil), data...)
	corrupted[len(corrupted)/2] ^= 0x01
	if got := verifyPackageBytes(assetURL, ".ipk", corrupted); got.Status != "mismatch" || !got.fatal() {
		t.Fatalf("a one-byte-corrupted copy of the release asset was NOT rejected: %+v", got)
	} else {
		t.Logf("corrupted copy rejected as expected: %s", got.Detail)
	}
}

// TestInstallStepStatusNeverGreensAnUnverifiedInstall pins finding 1 of the cold
// cross-family review (2026-09-23): step 6 may render GREEN only for a verdict
// that verified the bytes against an INDEPENDENT published digest. Before this,
// the render demoted exactly one status ("unverified") and nothing else, so a
// zero-value verdict — an install path that never consulted the gate at all,
// e.g. the router's own package feed — rendered a green "done" with NO integrity
// suffix, indistinguishable from a verified install.
func TestInstallStepStatusNeverGreensAnUnverifiedInstall(t *testing.T) {
	cases := []struct {
		name string
		v    pkgIntegrity
		want string
	}{
		{"verified", pkgIntegrity{Status: "verified"}, "done"},
		{"unverified", pkgIntegrity{Status: "unverified"}, "warn"},
		{"zero value: the gate never ran", pkgIntegrity{}, "warn"},
		{"mismatch", pkgIntegrity{Status: "mismatch"}, "warn"},
		{"malformed", pkgIntegrity{Status: "malformed"}, "warn"},
	}
	for _, c := range cases {
		if got := installStepStatus(c.v); got != c.want {
			t.Errorf("installStepStatus(%s) = %q, want %q", c.name, got, c.want)
		}
	}
}

// TestRouterFeedInstallVerdictIsUnverifiedAndLegible pins that the last-resort
// install from the ROUTER's own configured feeds cannot be reported as verified:
// those bytes never passed through this installer, so no published digest was
// ever checked against them.
func TestRouterFeedInstallVerdictIsUnverifiedAndLegible(t *testing.T) {
	v := routerFeedInstallVerdict()
	if v.verified() || v.fatal() {
		t.Fatalf("router-feed verdict = %+v, want unverified and non-fatal", v)
	}
	if v.suffix() != " [sha256 NOT VERIFIED]" {
		t.Errorf("suffix = %q, want the NOT VERIFIED marker", v.suffix())
	}
	if installStepStatus(v) != "warn" {
		t.Errorf("step status = %q, want warn for an install the gate never saw", installStepStatus(v))
	}
	if !strings.Contains(v.Detail, "never passed through this installer") {
		t.Errorf("detail = %q, want it to say why nothing could be verified", v.Detail)
	}
}
